on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Site
        run: |
          npm install yarn -g
          yarn install
          yarn build
      - name: Deploy to Uplink
        uses: https://github.com/shallwefootball/upload-s3-action@master
        with:
          aws_key_id: ${{ secrets.STORJ_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.STORJ_SECRET_ACCESS_KEY }}
          endpoint: ${{ secrets.STORJ_ENDPOINT }}
          aws_bucket: ${{ secrets.STORJ_BUCKET }}
          source_dir: "dist"
          destination_dir: "hack13-site"
