on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Site
        run: |
          npm install yarn -g
          yarn install
          yarn build
      - name: Deploy to Uplink
        uses: https://github.com/shallwefootball/upload-s3-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STORJ_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORJ_SECRET_ACCESS_KEY }}
          ENDPOINT: ${{ secrets.STORJ_ENDPOINT }}
          AWS_BUCKET: ${{ secrets.STORJ_BUCKET }}
          SOURCE_DIR: "dist"
          DEST_DIR: "hack13-site"
