on: push
name: Build and Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Setup NodeJS env
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn
    - name: Build site
      run: yarn build
    - name: Upload files
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        host: ${{ secrets.SFTP_SERVER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
        localDir: 'dist'
        remoteDir: ${{ secrets.SFTP_REMOTE_PATH }}